http://www.abclinuxu.cz/blog/pyx/2011/10/dsl.sk
HTTP/1.1 200 OK
Server: nginx/0.7.67
Date: Thu, 24 Jul 2014 06:23:03 GMT
Content-Type: text/html;charset=UTF-8
Connection: close
Set-Cookie: JSESSIONID=10c41aylm66sz1slub26ivrblx;Path=/
Expires: Fri, 22 Dec 2000 05:00:00 GMT
Last-Modified: Thu, 24 Jul 2014 06:23:03 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Content-Length: 15138
Content-Encoding: gzip



<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/1998/REC-html40-19980424/strict.dtd" >
<html lang="cs">
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Robots" content="index,follow">
    <title>h8blog, m8</title>
    <link rel="stylesheet" type="text/css" href="/jquery-theme/ui.all.css">
    <link rel="stylesheet" type="text/css" href="/data/site/prettyPhoto/prettyPhoto.css">
    <link rel="stylesheet" type="text/css" href="/styles.css">
    
    <!--[if IE]>
       <link href="/msie.css" type="text/css" rel="stylesheet">
    <![endif]-->
    <!--[if IE 7]>
       <link href="/msie7.css" type="text/css" rel="stylesheet">
    <![endif]-->
    <!--[if lt IE 7]>
       <link href="/msie6.css" type="text/css" rel="stylesheet">
    <![endif]-->
    <link rel="icon" href="/images/site2/favicon.png" type="image/png">
        <link rel="alternate" title="RSS zdroj aktuální sekce" href="http://www.abclinuxu.cz/auto/blog/pyx.rss" type="application/rss+xml">


    <script type="text/javascript" src="/data/site/jquery/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/data/site/prettyPhoto/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="/data/site/scripts.js"></script>
        <script type="text/javascript" src="/data/syntaxhighlighter/scripts/all.js"></script>
    <script type="text/javascript">
    	Page = new Object();
        	Page.relationID = 176425;
    </script>
</head>

<body id="www-abclinuxu-cz">

<!-- the advertisement position netmonitor is not active -->
<!-- ad position 'ad-init' -->
<!-- (C)2000-2013 Gemius SA - gemiusAudience / abclinuxu.cz / Ostatni stranky -->
<script type="text/javascript">
<!--//--><![CDATA[//><!--
var pp_gemius_identifier = 'nAibwgxfLImzY0xcXtikzGaDTM3ZI5CjEvS.n4fTUsn.g7';
// lines below shouldn't be edited
function gemius_pending(i) { window[i] = window[i] || function() {var x = window[i+'_pdata'] = window[i+'_pdata'] || []; x[x.length]=arguments;};};
gemius_pending('gemius_hit'); gemius_pending('gemius_event'); gemius_pending('pp_gemius_hit'); gemius_pending('pp_gemius_event');
(function(d,t) {try {var gt=d.createElement(t),s=d.getElementsByTagName(t)[0]; gt.setAttribute('async','async'); gt.setAttribute('defer','defer');
 gt.src='http://spir.hit.gemius.pl/xgemius.js'; s.parentNode.insertBefore(gt,s);} catch (e) {}})(document,'script');
//--><!]]>
</script>
<!-- ad position 'sf-lista' -->
<div class="sflista">
     <div class="ri">
    	<!--<a href="http://www.stickfish.com" title="Guarantee business interface.">
	<img src="/images/site2/sflista/sf.gif" alt="Guarantee business interface."> stickfish.com</a>-->
     </div>
     <div class="le">
        <a href="http://www.abclinuxu.cz" title="Linux na stříbrném podnose."><img src="/images/site2/sflista/ab.gif" alt="abclinuxu.cz"> AbcLinuxu.cz</a>
        <a href="http://www.itbiz.cz" title="IT business."><img src="/images/site2/sflista/ib.gif" alt="itbiz.cz"> ITBiz.cz</a>
        <a href="http://www.hdmag.cz/" title="HDmag.cz | Vysoké rozlišení od začátku do konce. Blu-ray filmy, přehrávače, HDTV, HD audio a video, PlayStation 3..."><img src="/images/site2/sflista/hd.gif" alt="HDmag.cz"> HDmag.cz</a>
        <a href="http://www.abcprace.cz" title="Spojujeme lidi s prací v IT!"><img src="/images/site2/sflista/pr.gif" alt="abcprace.cz"> AbcPráce.cz</a>
     </div>
    <div class="cistic"></div>
</div>
<!-- error: no variant available for position 'leaderboard', code 'null' -->
<div id="zh-kont">
    <div id="zh-text" class="zh-box">
<!-- ad position 'zahl-vlevo' -->
<div id="zh-tema">
<!--<table border="0" cellpadding="0" cellspacing="0">
<tr><td colspan="6">Sledujte AbcLinuxu.cz na:</td></tr>
<tr>
<td><img src="/images/site2/facebook-favicon.gif" alt="facebook favicon logo"></td>
<td class="reverse_anchor">&nbsp;<a href="http://www.facebook.com/pages/AbcLinuxucz/68355234681">Facebooku</a>,&nbsp;</td>

<td><img src="/images/site2/twitter-favicon.gif" alt="twitter favicon logo"></td>
<td class="reverse_anchor">&nbsp;<a href="http://twitter.com/abclinuxu">Twitteru</a>, &nbsp;</td>

<td><img src="/images/site2/identica-favicon.gif" alt="identi.ca favicon logo"></td>
<td class="reverse_anchor">&nbsp;<a href="http://identi.ca/abclinuxu">Identi.ca</a>, &nbsp;</td>

<td><img src="/images/site2/feed16.png" alt="rss logo"></td>
<td class="reverse_anchor">&nbsp;<a href="/napoveda/rss-a-jine-pristupy">RSS</a></td>

</tr>
</table>-->


<div style="line-height: 35px"><img src="/images/site2/sflista/ab.gif" style="vertical-align: middle">AbcLinuxu <a href="/portal/wiki/namety-na-clanky">hledá autory</a>!</div>


</div><!-- ad position 'zahl-vpravo' -->
<div id="zh-ad" style="line-height:35px">
   <!--<a href="/clanky/openmagazin-3-2010"><img class="zh-iko" src="/images/clanky/redakce/openmagazin-logo-90x45.png" alt="openmagazin logo" width="90" height="45"></a>
    <a href="/clanky/openmagazin-3-2010">openMagazin 3/2010</a>-->
    <!--<a href="/clanky/anketa-o-distribuci-2010"><img class="zh-iko" src="/images/clanky/redakce/distribuce-roku-2010-logo-41x45.png" alt="distribuce roku 2010" width="41" height="45"></a>
    <a href="/clanky/anketa-o-distribuci-2010"><b>Hlasujte</b> o nejoblíbenější distribuci!</a>-->

<img src="/images/site2/sflista/pr.gif" alt="" style="vertical-align: middle"> <!--<a href="/blog/doli/2011/8/abclinuxu-hleda-autory">Pište</a> pro AbcLinuxu!-->
<a href="http://www.abcprace.cz/co-nabizime/">Inzerujte</a> na AbcPráce.cz od 950&nbsp;Kč
</div><!-- the advertisement position zahl-komplet is not active -->    </div>
    <div id="zh-logo" class="zh-box"><a href="/"></a></div>
    <div id="zh-hledani" class="zh-box">
        <form action="/hledani" method="get">
            <div>
                <input type="text" class="text" name="dotaz">
                <input class="button" type="submit" value="Hledej">
            </div>
        </form>
        <a href="/hledani?action=toAdvanced">Rozšířené hledání</a>
    </div>
</div>
<div class="cistic"></div>

<div id="menu-wrap">
<b style="font-size:0px;display:block; background:transparent;">
 <b class="roh1"></b><b class="roh2"></b>
</b>
<div class="menu-kont">

<ul class="menu" id="menu">
<li><a href="/poradna">Poradna</a>
  <ul>
    <li><a href="/poradna/linux">Linuxová poradna</a></li>
    <li><a href="/poradna/databaze">Databázová poradna</a></li>
    <li><a href="/poradna/programovani">Programovací poradna</a></li>
    <li><a href="/poradna/hardware">Hardwarová poradna</a></li>
    <li><a href="/poradna/unix">Unixová poradna</a></li>
  </ul></li>
<li><a href="/faq">FAQ</a></li>
<li><a href="/hardware">Hardware</a>
  <ul>
    <li><a href="/ovladace">Ovladače</a></li>
    <li><a href="/hardware/procesory">Procesory</a></li>
    <li><a href="/hardware/pridavne-karty">Přídavné karty</a></li>
    <li><a href="/hardware/pripojeni-na-sit">Připojení na síť</a></li>
    <li><a href="/hardware/prislusenstvi">Příslušenství</a></li>
    <li><a href="/hardware/sestavy">Sestavy</a></li>
    <li><a href="/hardware/ukladani-dat">Ukládání dat</a></li>
    <li><a href="/hardware/vstupni-zarizeni">Vstupní zařízení</a></li>
    <li><a href="/hardware/vystupni-zarizeni">Výstupní zařízení</a></li>
    <li><a href="/hardware/zakladni-desky">Základní desky</a></li>
  </ul></li>
<li><a href="/software">Software</a>
  <ul>
    <li><a href="/software/alternativy">Alternativy k aplikacím</a></li>
    <li><a href="/software/bezpecnost">Bezpečnost</a></li>
    <li><a href="/software/grafika">Grafika</a></li>
    <li><a href="/software/hobby">Hobby</a></li>
    <li><a href="/software/hry">Hry</a></li>
    <li><a href="/software/internet">Internet</a></li>
    <li><a href="/software/kancelar">Kancelář</a></li>
    <li><a href="/software/multimedia">Multimédia</a></li>
    <li><a href="/software/nastroje">Nástroje</a></li>
    <li><a href="/software/pracovni-prostredi">Pracovní prostředí</a></li>
    <li><a href="/software/programovani">Programování</a></li>
    <li><a href="/software/server">Server</a></li>
    <li><a href="/software/soubory">Soubory</a></li>
    <li><a href="/software/system">Systém</a></li>
    <li><a href="/software/vzdelavani">Vzdělávání</a></li>
    <li><a href="/software/veda">Věda</a></li>
  </ul></li>
<li><a href="/clanky">Články</a>
  <ul>
    <li><a href="/clanky/bezpecnost">Bezpečnost</a></li>
    <li><a href="/clanky/hardware">Hardware</a></li>
    <li><a href="/clanky/hry-a-zabava">Hry a zábava</a></li>
    <li><a href="/clanky/jaderne-noviny">Jaderné noviny</a></li>
    <li><a href="/clanky/multimedia">Multimédia</a></li>
    <li><a href="/clanky/navody">Návody</a></li>
    <li><a href="/clanky/novinky">Novinky</a></li>
    <li><a href="/clanky/programovani">Programování</a></li>
    <li><a href="/clanky/recenze">Recenze</a></li>
    <li><a href="/clanky/rozhovory">Rozhovory</a></li>
    <li><a href="/clanky/ruzne">Různé</a></li>
    <li><a href="/clanky/site">Sítě</a></li>
    <li><a href="/clanky/system">Systém</a></li>
    <li><a href="/clanky/tipy">Tipy a triky</a></li>
    <li><a href="/clanky/pr" style="border-width:3px">Tiskové zprávy</a></li>
    <li><a href="/serialy">Seriály</a></li>
  </ul></li>
<li><a href="/ucebnice">Učebnice</a>
  <ul>
    <li><a href="/ucebnice/uvod">Úvod</a></li>
    <li><a href="/ucebnice/obsah">Obsah</a></li>
    <li><a href="/ucebnice/historie">Historie Linuxu</a></li>
    <li><a href="/ucebnice/zaklady">Základy Linuxu</a></li>
    <li><a href="/ucebnice/prehled-prikazu">Přehled příkazů</a></li>
  </ul></li>
<li><a href="/blog">Blogy</a>
  <ul>
    <li><a href="/blog/vyber">Výběr (linuxové)</a></li>
    <li><a href="/blog/souhrn">Stručný souhrn</a></li>
    <li><a href="/blogy">Seznam blogů</a></li>
  </ul></li>
<li>
    <a href="/skupiny">Skupiny</a>
    <ul>
                    <li><a href="/portal">Portál</a></li>
            <li><a href="/tex">TeX</a></li>
            <li><a href="/datove-schranky">Datové schránky</a></li>
            <li><a href="/arch-linux">Arch Linux</a></li>
            <li><a href="/openmoko">Openmoko</a></li>
    </ul>
</li>
<li><a href="/desktopy">Desktopy</a></li>
<li><a href="/hry">Hry</a></li>
<li><a href="/slovnik">Slovník</a></li>
<li><a href="/kdo-je">Kdo je</a></li>
<li><a href="/bazar">Bazar</a></li>
<li><a href="/">Portál</a>
  <ul>
    <li><a href="/nej">Žebříčky a statistiky</a></li>
    <li><a href="/clanky/novinky/pojdte-psat-pro-abclinuxu.cz">Jak se stát autorem</a></li>
    <li><a href="/redakce">Redakce</a></li>
    <li><a href="/portal/propagace">Propagace</a></li>
    <li><a href="/reklama">Inzerce</a></li>
    <li><a href="/napoveda/rss-a-jine-pristupy">RSS feedy a PDA</a></li>
    <li><a href="http://bugzilla.abclinuxu.cz"  title="Požadavky týkající se funkčnosti portálu" rel="nofollow">Bugzilla - chyby a náměty</a></li>
    <li><a href="/pozadavky" title="Požadavky týkající se obsahu portálu">Vzkazy správcům (66)</a></li>
    <li><a href="/vyvoj">Zdrojové kódy</a></li>
    <li><a href="javascript:addSidebar();">Přidej sidebar</a></li>
    <li><a href="javascript:addBookmark();">Přidej mezi oblíbené</a></li>
    <li><a href="javascript:setHomepage();">Nastav jako domácí stránku</a></li>
  </ul></li>
<li><a href="http://www.abcprace.cz">Práce</a></li>
<li><a href="/napoveda/mapa-serveru" title="Mapa stránek a dalších služeb">Mapa</a></li>
</ul>

</div>
</div>
<!--[if IE]><br style="font-size:0"><![endif]-->

<div class="obal">

    <div class="hl">
        <div class="hl_vpravo">
                <a href="/Profile;jsessionid=10c41aylm66sz1slub26ivrblx?action=login">Přihlášení</a> |
                <a href="/EditUser;jsessionid=10c41aylm66sz1slub26ivrblx?action=register">Registrace</a>
        </div>
        <div class="hl_vlevo">
            <ul class="menu-top">
                <li>
                    <a href="/doc/napoveda/alternativni-design">Styl</a>
                    <ul class="menu-drop">
                        <li>
                            <a href="/EditUser/?action=changeStyle&amp;css=">Standardní světlý</a>
                        </li>
                        <li>
                            <a href="/EditUser/?action=changeStyle&amp;css=/styles-dark.css">Oficiální tmavý</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    <div id="ls_prepinac" title="Skrýt sloupec" onclick="prepni_sloupec()">&#215;</div>

    <div class="obal_ls" id="ls">
        <div class="s">
<!-- ad position 'vip' -->
<!-- BBelements AdServer one2many Pozice: go.cz.bbelements.com AbcLinuxu.cz(14398) / Zbytek webu(2) / VIP square dynamický(1) / square(2)-->
<!-- HowTo: Place this code into the html page there the ad should appear. -->
<div id='bmone2n-14398.2.1.2'>
<noscript><div style='display:inline'><a href='http://go.cz.bbelements.com/please/redirect/14398/2/1/2/'><img src='http://go.cz.bbelements.com/please/showit/14398/2/1/2/?typkodu=img' width='0' height='0' style='border-width:0' alt='' /></a></div></noscript>
</div><!-- the advertisement position vip-text is not active --><!-- ad position 'itbiz' -->
<div class="s_nadpis noext">
   <a class="s_nadpis-pravy-odkaz" href="http://www.itbiz.cz"><img src="/images/site2/itbiz-minilogo.png" alt="itbiz logo" style="margin-top:0.2em"></a>
   <a href="http://www.itbiz.cz">Píšeme jinde</a>
</div>
<div class="s_sekce">
<ul class="noext">
<li><a href="http://www.itbiz.cz/zpravicky/chyba-v-toru-umoznuje-odhalit-identitu-uzivatele">Chyba v Toru umožňuje odhalit identitu uživatele</a></li>
<li><a href="http://www.itbiz.cz/clanky/lide-ve-firmach-filip-svab-novym-executive-directorem-pro-mezinarodni-zalezitosti-ve-spolecnosti-at-t-a-jine-novinky">Lidé ve firmách: Filip Šváb novým executive directorem pro mezinárodní záležitos</a></li>
<li><a href="http://www.itbiz.cz/clanky/paradox-zen-v-it-cim-vic-se-o-nich-mluvi-tim-mene-jich-je">Paradox žen v IT: čím víc se o nich mluví, tím méně jich je</a></li>
<li><a href="http://www.itbiz.cz/zpravicky/druheho-service-packu-windows-8-se-dockame-v-srpnu">Druhého service packu Windows 8 se dočkáme v srpnu</a></li>
<li><a href="http://www.itbiz.cz/zpravicky/sap-za-q2-vydelala-4-2-miliardy-euro">SAP za Q2 vydělal 4,2 miliardy euro</a></li>
</ul>
</div>
            <!-- ZPRÁVIČKY -->
            <div class="s_nadpis">
                <a class="s_nadpis-pravy-odkaz" href="/zpravicky/edit;jsessionid=10c41aylm66sz1slub26ivrblx?action=add">napište &raquo;</a>
                <a href="/zpravicky" title="zprávičky">Zprávičky</a>
            </div>

<!-- ad position 'hypertext1' -->
<!-- BBelements AdServer one2many Pozice: go.cz.bbelements.com AbcLinuxu.cz(14398) / Zbytek webu(2) / hypertext(4) / Uživatelem definovaný rozměr 250x40(64)-->
<!-- HowTo: Place this code into the html page there the ad should appear. -->
<div style="margin-left: 10px"><div id='bmone2n-14398.2.4.64'></div></div>

<!-- BBelements one2many Pozice: AbcLinuxu.cz(14398) / Zbytek webu(2) / textbox(5) / Uživatelem definovaný rozměr 250x250(64) -->
<!-- HowTo: Place this code into the html page there the ad should appear. -->
<div id='bmone2n-14398.2.5.64'>
<noscript><div style='display:inline'><a href='http://go.cz.bbelements.com/please/redirect/14398/2/5/64/'><img src='http://go.cz.bbelements.com/please/showit/14398/2/5/64/?typkodu=img' width='250' height='250' style='border-width:0' alt='' /></a></div></noscript>
</div>
            <div class="s_sekce">
                <div class="ls_zpr">

        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/urad-vlady-spojeneho-kralovstvi-urcil-formaty-vladnich-dokumentu" title="Úřad vlády Spojeného království určil formáty vládních dokumentů">Úřad vlády Spojeného království určil formáty vládních dokumentů</a>
        </div>
    <span>včera 21:01 | Zajímavý článek</span>
        <div class="zpr_telo">Úřad vlády Spojeného království Velké Británie a Severního Irska <a href="https://www.gov.uk/government/news/open-document-formats-selected-to-meet-user-needs">určil</a> 
formáty vládních dokumentů (<a href="https://www.gov.uk/government/publications/open-standards-for-government">Open standards for government</a>). Pro <a href="https://www.gov.uk/government/publications/open-standards-for-government/sharing-or-collaborating-with-government-documents">sdílení a spolupráci</a> na dokumentech je to formát OpenDocument (<a href="http://cs.wikipedia.org/wiki/OpenDocument">ODF</a>) 1.2 a vyšší. Pro <a href="https://www.gov.uk/government/publications/open-standards-for-government/viewing-government-documents">prohlížení</a> dokumentů je to HTML5 a PDF/A. [<a href="http://www.reddit.com/r/linux/comments/2bfcne/uk_government_selects_odfpdf_as_sole_open/">reddit</a>]</div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/urad-vlady-spojeneho-kralovstvi-urcil-formaty-vladnich-dokumentu" title="poslední&nbsp;dnes 08:00">Komentářů:&nbsp;6</a></span>
                    <hr>
<!-- the advertisement position sl-box1 is not active -->
        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/firefox-31.0" title="Firefox 31.0">Firefox 31.0</a>
        </div>
    <span>včera 11:11 | Nová verze</span>
        <div class="zpr_telo">Byl vydán Mozilla Firefox 31.0. Nejviditelnější novinkou je přidání vyhledávacího pole na stránku nového panelu. Z dalších novinek lze zmínit například podporu nové HTTP hlavičky Prefer:Safe.  Nástroje pro vývojáře nově obsahují Add-on Debugger, Canvas Debugger a kapátko na snímání barev ze stránky [<a href="http://www.mozilla.cz/zpravicky/vysel-firefox-31-s-rozsirenou-podporou/">Mozilla.cz</a>]. Řešeny jsou také <a href="https://www.mozilla.org/security/known-vulnerabilities/firefox.html">bezpečnostní problémy</a>. Podrobnější informace v <a href="http://www.mozilla.org/en-US/firefox/31.0/releasenotes/">poznámkách k vydání</a>. Firefox 31 je nová verze s prodlouženou podporou (<a href="https://www.mozilla.org/en-US/firefox/organizations/all/">ESR</a>). Současně s Firefox 31 byl vydán také Firefox <a href="https://www.mozilla.org/en-US/firefox/24.7.0/releasenotes/">24.7.0</a>, tj. předchozí verze s prodlouženou podporou.</div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/firefox-31.0" title="poslední&nbsp;dnes 07:12">Komentářů:&nbsp;15</a></span>
                    <hr>
<!-- the advertisement position sl-box2 is not active -->
        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/konference-oscon-2014" title="Konference OSCON 2014">Konference OSCON 2014</a>
        </div>
    <span>22.7. 10:35 | Komunita</span>
        <div class="zpr_telo">V Portlandu probíhá pětidenní konference <a href="http://www.oscon.com/oscon2014">OSCON 2014</a> (O'Reilly Open Source Convention). Po dvou dnech <a href="http://www.oscon.com/oscon2014/public/schedule/stype/tutorial">tutoriálů</a> dnes začínají přednášky. Úvodní přednášky (keynotes) je možné sledovat <a href="http://oscon.com/live">online</a>. Videozáznamy všech tutoriálů a přednášek (<a href="http://www.oscon.com/oscon2014/public/schedule/grid/public">program</a>) budou k dispozici po skončení konference.</div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/konference-oscon-2014" title="poslední&nbsp;22.7. 14:27">Komentářů:&nbsp;1</a></span>
                    <hr>
<!-- ad position 'sl-mini' -->
<!-- BBelements one2many Pozice: AbcLinuxu.cz(14398) / Zbytek webu(2) / textbox-spodni(7) / Uživatelem definovaný rozměr 250x250(64) -->
<!-- HowTo: Place this code into the html page there the ad should appear. -->
<div id='bmone2n-14398.2.7.64'>
<noscript><div style='display:inline'><a href='http://go.cz.bbelements.com/please/redirect/14398/2/7/64/'><img src='http://go.cz.bbelements.com/please/showit/14398/2/7/64/?typkodu=img' width='250' height='250' style='border-width:0' alt='' /></a></div></noscript>
</div>
        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/debian-jessie-prechazi-na-systemd" title="Debian Jessie přechází na systemd">Debian Jessie přechází na systemd</a>
        </div>
    <span>21.7. 20:23 | Upozornění</span>
        <div class="zpr_telo">Poslední upgrade Debianu Testing/Jessie přináší systemd jako náhradu za sysvinit. Ačkoli byl funkční systemd součástí Debianu Jessie již delší dobu, nebyl používán pro spouštění systému. <a href="https://wiki.debian.org/systemd#Installing_and_Testing">Toho bylo možné docílit</a> parametrem jádra při spuštění systému, kdy nebyl původní sysvinit nijak dotčen, nebo instalací balíku systemd-sysv, který původní init nahrazuje symlinkem na systemd. Tento balík je nicméně součástí posledního upgradu &hellip;&nbsp;<i><a href="/zpravicky/debian-jessie-prechazi-na-systemd">více&nbsp;&raquo;</a></i></div>
    <span><a href="/lide/cyder">Migilenik</a>
    | <a href="/zpravicky/debian-jessie-prechazi-na-systemd" title="poslední&nbsp;dnes 01:02">Komentářů:&nbsp;139</a></span>
                    <hr>
<!-- ad position 'skyscraper' -->
<!-- iBILLBOARD Ad Server one2many Pozice: go.cz.bbelements.com AbcLinuxu.cz(14398) / Zbytek webu(2) / skyscraper(4) / 468x60(1)-->
<!-- HowTo: Place this code into the html page where the ad should appear. -->
<div id='bmone2n-14398.2.4.1'>
<noscript><div style='display:inline'><a href='http://go.cz.bbelements.com/please/redirect/14398/2/4/1/'><img src='http://go.cz.bbelements.com/please/showit/14398/2/4/1/?typkodu=img' width='0' height='0' style='border-width:1' alt='' /></a></div></noscript>
</div><!-- the advertisement position double-sky is not active -->
        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/apache-http-server-2.4.10" title="Apache HTTP Server 2.4.10">Apache HTTP Server 2.4.10</a>
        </div>
    <span>21.7. 17:28 | Bezpečnostní upozornění</span>
        <div class="zpr_telo"><a href="http://www.apache.org/dist/httpd/Announcement2.4.html">Vyšla</a> verze 2.4.10 webového serveru Apache. Nejnovější verze řeší především <a href="http://httpd.apache.org/security/vulnerabilities_24.html">5 bezpečnostních problémů</a> (CVE-2014-0231, CVE-2014-3523, CVE-2014-0117, CVE-2014-0118, CVE-2014-0226).</div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/apache-http-server-2.4.10" title="poslední&nbsp;21.7. 22:44">Komentářů:&nbsp;2</a></span>
                    <hr>

        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/ohloh-prejmenovan-na-black-duck-open-hub" title="Ohloh přejmenován na Black Duck Open Hub">Ohloh přejmenován na Black Duck Open Hub</a>
        </div>
    <span>21.7. 15:58 | Komunita</span>
        <div class="zpr_telo">Projekt Ohloh (<a href="http://en.wikipedia.org/wiki/Ohloh">Wikipedia</a>), informace a statistiky o otevřených softwarových projektech, byl <a href="http://blog.openhub.net/2014/07/black-duck-open-hub/">přejmenován</a> na Black Duck Open Hub.

&hellip;&nbsp;<i><a href="/zpravicky/ohloh-prejmenovan-na-black-duck-open-hub">více&nbsp;&raquo;</a></i></div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/ohloh-prejmenovan-na-black-duck-open-hub" title="poslední&nbsp;21.7. 20:47">Komentářů:&nbsp;3</a></span>
                    <hr>

        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/konference-hope-x" title="Konference HOPE X">Konference HOPE X</a>
        </div>
    <span>20.7. 13:00 | Komunita</span>
        <div class="zpr_telo">V New Yorku probíhá konference <a href="http://x.hope.net/">HOPE X</a>. Jedná se o 10. konferenci HOPE (<a href="http://en.wikipedia.org/wiki/Hackers_on_Planet_Earth">Hackers On Planet Earth</a>). Konferenci je možné sledovat <a href="http://x.hope.net/stream.html">online</a> (<a href="http://x.hope.net/grid.html">časový harmonogram</a>).
Videozáznamy proběhlých přednášek jsou k dispozici na Livestreamu (<a href="http://new.livestream.com/internetsociety/hopex1">Manning</a>, <a href="http://new.livestream.com/internetsociety2/hopex2">Serpico</a>, <a href="http://new.livestream.com/internetsociety3/hopex3">Olson</a>).</div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/konference-hope-x" title="poslední&nbsp;21.7. 13:16">Komentářů:&nbsp;5</a></span>
                    <hr>

        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/domaci-pracovna-linuse-torvaldse" title="Domácí pracovna Linuse Torvaldse">Domácí pracovna Linuse Torvaldse</a>
        </div>
    <span>18.7. 07:56 | Zajímavý článek</span>
        <div class="zpr_telo">Díky Linux Foundation lze <a href="http://www.linuxfoundation.org/news-media/blogs/browse/2014/07/linux-creator-linus-torvalds-your-guide-rare-look-inside-his-home">nahlédnout</a> (<a href="http://www.youtube.com/watch?v=HSgUPqygAww">YouTube</a>) do domácí pracovny Linuse Torvaldse. Linus Torvalds mimo jiné předvádí svůj počítačový stůl spojený s běžeckým pásem (<a href="http://en.wikipedia.org/wiki/Treadmill_desk">Treadmill desk</a>).</div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/domaci-pracovna-linuse-torvaldse" title="poslední&nbsp;dnes 07:50">Komentářů:&nbsp;291</a></span>
                    <hr>
<!-- error: no variant available for position 'sl-dole', code '.*' -->
        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/android-wear-hackathon-v-prazskem-techsquare-se-blizi" title="Android Wear hackathon v pražském TechSquare se blíží">Android Wear hackathon v pražském TechSquare se blíží</a>
        </div>
    <span>17.7. 22:42 | Pozvánky</span>
        <div class="zpr_telo"><a href="http://www.gug.cz/cs/gdg/skupiny/prague">GDG Prague</a> a <a href="http://www.inmite.eu/">Inmite</a> vás zvou na další zajímavý hackathon. Tentokrát se budou vytvářet aplikace pro chytré hodinky Android Wear, které byly představeny před měsícem na konferenci Google I/O. Na místě bude k dispozici několik hodinek na testování. Nejlepší aplikace mohou vyhrát zajímavé ceny.
&hellip;&nbsp;<i><a href="/zpravicky/android-wear-hackathon-v-prazskem-techsquare-se-blizi">více&nbsp;&raquo;</a></i></div>
    <span><a href="/lide/destil">Destil</a>
    | <a href="/zpravicky/android-wear-hackathon-v-prazskem-techsquare-se-blizi" title="">Komentářů:&nbsp;0</a></span>
                    <hr>

        <div class="st_nadpis no_overflow">
            <a href="/zpravicky/textove-editory-ve-fedore-1.-cast" title="Textové editory ve Fedoře (1. část)">Textové editory ve Fedoře (1. část)</a>
        </div>
    <span>17.7. 17:00 | Zajímavý článek</span>
        <div class="zpr_telo">Pavel Tišnovský se v článku <a href="http://fedora.cz/textove-editory-ve-fedore-1-cast/">Textové editory ve Fedoře (1. část)</a> na Fedora.cz věnuje konzolovým textovým editorům, jež jsou k dispozici nejenom ve Fedoře. Zabývá se editory e3, GNU nano, Jed, Joe a MCEdit (Midnight Commander Internal Editor).</div>
    <span><a href="/lide/ladislav.hagara">Ladislav Hagara</a>
    | <a href="/zpravicky/textove-editory-ve-fedore-1.-cast" title="poslední&nbsp;včera 15:16">Komentářů:&nbsp;3</a></span>
                    <hr>
                </div>
                <div class="s_odkaz">
                    <a href="/zpravicky">Centrum</a> |
                    <a href="/zpravicky/edit;jsessionid=10c41aylm66sz1slub26ivrblx?action=add" rel="nofollow">Napsat</a> |
                    <a href="/History?type=news&amp;from=10&amp;count=15">Starší</a>
                </div>
            </div>

            <!-- ANKETA -->

                <div class="s_nadpis">
                   <a class="s_nadpis-pravy-odkaz" href="/pozadavky?categoryPosition=0">navrhněte&nbsp;&raquo;</a>
                   <a href="/ankety">Anketa</a>
                </div>
                <div class="s_sekce">
                    <form action="/EditPoll/390415;jsessionid=10c41aylm66sz1slub26ivrblx" method="POST">
                     <div class="ank-otazka">Máte na svém notebooku zašifrovaný pevný disk?</div>
                        <div class="ank-odpov">
                          <label><input type="radio" name="voteId" value="0">Ano</label>&nbsp;(<span title="5674">89%</span>)<br>
                          <div class="ank-sloup-okraj" style="width: 89px">
                            <div class="ank-sloup"></div>
                          </div>
                        </div>
                        <div class="ank-odpov">
                          <label><input type="radio" name="voteId" value="1">Ne</label>&nbsp;(<span title="688">11%</span>)<br>
                          <div class="ank-sloup-okraj" style="width: 11px">
                            <div class="ank-sloup"></div>
                          </div>
                        </div>
                     <div>
                      <input name="submit" type="submit" class="button" value="Hlasuj" alt="Hlasuj">
                        Celkem 6362 hlasů
                      <input type="hidden" name="url" value="/ankety/zasifrovany-disk-notebook">
                      <input type="hidden" name="action" value="vote">
                     </div>
                    </form>
                </div>
                <div>&nbsp;<a href="/ankety/zasifrovany-disk-notebook">Komentářů: 45</a>, poslední 21.7. 22:10
<!-- the advertisement position anketa is not active -->                </div>

<!-- ad position 'sl-jobscz' -->
<div id="jobs" class="noext">
	<div class="jobs-ad-box">
		<div class="jobs-ad-header"><a href="http://www.jobs.cz/" class="jobs-ad-title" title="Jobs.cz - aktuální nabídka práce nejen v informačních technologiích">Práce v IT</a>
		<a href="http://www.jobs.cz/" class="jobs-ad-logo" title="Jobs.cz - aktuální nabídka práce"></a>
        <div class="jobs-ad-cb"></div>
	</div>
		<div id="jobs-in">
			<ul id="jobs-lst">
    <li><a href="http://www.jobs.cz/pd/857735706/?rps=74?fc=a-jobs&amp;fg=a-produkt&amp;fs=abclinuxu.cz&amp;fm=aliance&amp;ff=box&amp;fi=stickfish&amp;fb=it" rel="nofollow">SENIOR PROGRAMMER ANALYST PL/SQL</a></li>
    <li><a href="http://www.jobs.cz/pd/858543137/?rps=74?fc=a-jobs&amp;fg=a-produkt&amp;fs=abclinuxu.cz&amp;fm=aliance&amp;ff=box&amp;fi=stickfish&amp;fb=it" rel="nofollow">programátor junior</a></li>
    <li><a href="http://www.jobs.cz/pd/145904230/?rps=74?fc=a-jobs&amp;fg=a-produkt&amp;fs=abclinuxu.cz&amp;fm=aliance&amp;ff=box&amp;fi=stickfish&amp;fb=it" rel="nofollow">Inženýra pro testování SW (m/ž) - 2014</a></li>
    <li><a href="http://www.jobs.cz/pd/779537578/?rps=74?fc=a-jobs&amp;fg=a-produkt&amp;fs=abclinuxu.cz&amp;fm=aliance&amp;ff=box&amp;fi=stickfish&amp;fb=it" rel="nofollow">SW Engineer (Java + CMS)</a></li>
    <li><a href="http://www.jobs.cz/pd/742854508/?rps=74?fc=a-jobs&amp;fg=a-produkt&amp;fs=abclinuxu.cz&amp;fm=aliance&amp;ff=box&amp;fi=stickfish&amp;fb=it" rel="nofollow">Java Web Developer - international projects</a></li>
    <li><a href="http://www.jobs.cz/pd/55407565/?rps=74?fc=a-jobs&amp;fg=a-produkt&amp;fs=abclinuxu.cz&amp;fm=aliance&amp;ff=box&amp;fi=stickfish&amp;fb=it" rel="nofollow">Inženýra vývoj SW (m/ž)- C, C++  2014</a></li>
			</ul>
			<a class="jobs-ad-more" href="http://it.jobs.cz" title="Zobrazit další nabídky práce na serveru Jobs.cz nejen z IT">více nabídek práce &raquo;</a>
			<div class="jobs-ad-cb"></div>
		</div>
	</div>
<div class="jobs-bottom"><span>Tip:</span> <a href="http://www.jobs.cz/kurzy-a-skoleni/" title="Kurzy, školení, rekvalifikace, semináře - nová sekce vzdělávání na Jobs.cz">Školení, kurzy, semináře a rekvalifikace &raquo;</a></div>
</div><!-- ad position 'sl-abcprace' -->
<!-- abcprace.cz -->
<div class="s_nadpis noext">
   <a href="http://www.abcprace.cz/co-nabizime/" class="s_nadpis-pravy-odkaz">inzerujte »</a>
   <a href="http://www.abcprace.cz" title="Spojujeme lidi s prací v IT.">Pracovní nabídky</a>
</div>

<div class="s_sekce noext">
   <ul><li><a href="http://www.abcprace.cz/lukapo-s-r-o/linux-server-administrator">Linux Server Administrator</a></li>
</ul></div>
                    <!-- ROZCESTNÍK -->
                    <div class="s_nadpis">Rozcestník</div>
                    <div class="s_sekce">
                        <div class="rozc">
                                <a class="server" href="/presmeruj?class=S&amp;id=7&amp;url=http%3A%2F%2Fwww.abclinuxu.cz">AbcLinuxu</a><br>
                                <ul>
                                    <li>
                                        <a href="/presmeruj?class=S&amp;id=7&amp;url=http%3A%2F%2Fwww.abclinuxu.cznull">Roccat Lua a Zowie FK</a>
                                    </li>
                                    <li>
                                        <a href="/presmeruj?class=S&amp;id=7&amp;url=http%3A%2F%2Fwww.abclinuxu.cznull">Jaderné noviny – 3. 7. 2014: Další mechanismus pro sandboxování</a>
                                    </li>
                                </ul>
                                <a class="server" href="/presmeruj?class=S&amp;id=42&amp;url=http%3A%2F%2Fhdmag.cz%2F">HDmag.cz</a><br>
                                <ul>
                                    <li>
                                        <a href="/presmeruj?class=S&amp;id=42&amp;url=http%3A%2F%2Fhdmag.cz%2Fclanek%2Fgodzilla-na-blu-ray-zname-vsechny-bonusy">GODZILLA na Blu-ray: Známe všechny bonusy</a>
                                    </li>
                                    <li>
                                        <a href="/presmeruj?class=S&amp;id=42&amp;url=http%3A%2F%2Fhdmag.cz%2Fbleskovka%2Fstrazci-galaxie-reziser-james-gunn-mluvi-o-imaxu-a-3d">STRÁŽCI GALAXIE: Režisér James Gunn mluví o IMAXu a 3D</a>
                                    </li>
                                </ul>
                        </div>
                    </div>

<!-- ad position 'sl-doporucujeme' -->
<div class="s_nadpis">Reklama</div>
<div class="s_sekce noext">
  <ul>
    <li><a href="http://www.hosting90.cz">Hosting 90</a></li>
    <li><a href="http://www.linux.cz" rel="nofollow">linux.cz</a></li>
    
    <!--<li><a rel="nofollow" href="http://www.diit.cz">Deep in IT</a></li>
    <li><a href="http://www.svethardware.cz"  title="Informační technologie, počítače, hardware, recenze, testy, zpravodajství, diskuzní fórum">Svethardware.cz</a></li>
    <li><a href="http://www.tvfreak.cz"  title="Spotřební elektronika, televizní vysílání, video, recenze, testy, zpravodajství, diskuzní fórum">TVFreak.cz</a></li>-->
  </ul>
</div>

<div style="position: absolute; visibility: hidden">
    <a href="http://www.autonavody.cz/autoskola-testy-online">Autoškola testy online</a>
    <a href="http://www.autonavody.cz/levny-benzin">Levný benzín</a>
    </div>

<div style="width:250px; margin: 0.5em auto;" class="noext">
    <script src="http://www.argonit.cz/tmp/64bit.js"></script>
</div>
<!-- the advertisement position sl-placene-odkazy is not active -->
        </div> <!-- s -->
    </div> <!-- obal_ls -->

        <div class="obal_ps">
            <div class="ps"><div class="s">
               
<!-- the advertisement position hypertext2nahore is not active -->
    <div class="s_nadpis">
<a href="/lide/davkol">davkol</a>    	 - <a href="/blog/pyx">h8blog</a>
    </div>

    <div class="s_sekce">
        <p>A z kanálů se valej sračky, chcíplí psi a chcíplý mačky.</p>
<center>
<a href="http://www.nerdtests.com/ft_nq.php">
<img src="http://www.nerdtests.com/images/ft/nq/b1ccbdb62e.gif" alt="I am nerdier than 99% of all people. Are you a nerd? Click here to take the Nerd Test, get geeky images and jokes, and write on the nerd forum!"></a>
</center>
    </div>

        <div class="s_nadpis">Kategorie zápisků</div>
        <div class="s_sekce">
            <ul>
                        <li><a href="/blog/pyx/nic">nic</a></li>
                        <li><a href="/blog/pyx/otaznik">otazník (?)</a></li>
                        <li><a href="/blog/pyx/otaznik-a-vykricnik">otazník a vykřičník (?!)</a></li>
                        <li><a href="/blog/pyx/strednik">středník (;)</a></li>
                        <li><a href="/blog/pyx/tecka">tečka (.)</a></li>
                        <li><a href="/blog/pyx/vykricnik">vykřičník (!)</a></li>
            </ul>
        </div>




    <div class="s_nadpis">Aktuální zápisy</div>

    <div class="s_sekce">
        <ul>
            <li>
                <a href="/blog/pyx/2014/3/blackwidow-2014-razer-jsou-lhari-a-podvodnici" title="BlackWidow 2014: Razer jsou lháři a podvodníci">BlackWidow 2014: Razer jsou lháři a podvodníci</a>
            </li>
            <li>
                <a href="/blog/pyx/2014/5/dalsi-nechutny-utok-pohrbili-ivetu-bartosovou" title="Další nechutný útok: Pohřbili Ivetu Bartošovou!">Další nechutný útok: Pohřbili Ivetu Bartošovou!</a>
            </li>
            <li>
                <a href="/blog/pyx/2014/3/extreme-anime-avatars-the-legacy" title="eXtreme anime avatars: the legacy">eXtreme anime avatars: the legacy</a>
            </li>
            <li>
                <a href="/blog/pyx/2014/3/proc-se-na-hokej-nekoukam-rozhodci-t-t" title="Proč se na hokej nekoukám: rozhodčí T_T">Proč se na hokej nekoukám: rozhodčí T_T</a>
            </li>
            <li>
                <a href="/blog/pyx/2014/3/informatika-na-kmi-upol-report-za-4.-semestr" title="Informatika na KMI UPOL: report za 4. semestr">Informatika na KMI UPOL: report za 4. semestr</a>
            </li>
        </ul>
    </div>

    <div class="s_nadpis">
        <a class="info" href="#">?<span class="tooltip">Přístup k archivovaným zápisům za jednotlivé měsíce.</span></a>
        <a href="/blog/pyx/archiv">Archív</a>
    </div>

    <div class="s_sekce">
        <ul>
            <li>
                <a href="/blog/pyx/2014/7/">červenec
                2014 (1)</a>
            </li>
            <li>
                <a href="/blog/pyx/2014/5/">květen
                2014 (1)</a>
            </li>
            <li>
                <a href="/blog/pyx/2014/3/">březen
                2014 (6)</a>
            </li>
            <li>
                <a href="/blog/pyx/2014/2/">únor
                2014 (1)</a>
            </li>
            <li>
                <a href="/blog/pyx/2013/9/">září
                2013 (2)</a>
            </li>
            <li>
                <a href="/blog/pyx/2013/7/">červenec
                2013 (2)</a>
            </li>
        </ul>
    </div>


        <div class="s_nadpis">
            <a class="info" href="#">?<span class="tooltip">Poslední screenshot mého desktopu.</span></a>
            Současný desktop
        </div>

        <div class="s_sekce" align="center">
            <a href="/desktopy/davkol-20140702" title="Fingering a shark's anus..." class="thumb">
                <img src="/images/screenshots/2/8/206482-fingering-a-shark-s-anus-listing-165930872376257640.png" alt="Fingering a shark's anus..." border="0">
            </a>
        </div>

    <div class="s_nadpis">
        <a class="info" href="#">?<span class="tooltip">Přístup na osobní hlavní stranu a na hlavní stranu všech blogů.</span></a>
        Navigace
    </div>

    <div class="s_sekce">
        <ul>
                <li><a href="/blog/pyx">h8blog, hlavní strana</a></li>
            <li><a href="/blog/pyx/souhrn">h8blog, stručný souhrn</a></li>
            <li><a href="/auto/blog/pyx.rss">RSS kanál</a></li>
            <li><a href="/blog">Všechny blogy</a></li>
	        <li><a href="/blog/souhrn">Stručný souhrn blogů</a></li>
	        <li><a href="/blog/vyber">Výběr z blogů</a></li>
	        <li>
        <a href="/blog/EditMonitor/176425;jsessionid=10c41aylm66sz1slub26ivrblx?action=start">Začni sledovat</a>
    <span title="Počet lidí, kteří sledují tento dokument nebo sekci">(1)</span>
    <a class="info" href="#">?<span class="tooltip">Zašle upozornění na váš email při vytvoření nového zápisku v tomto blogu.</span></a>
            </li>
        </ul>
    </div>

<!-- ad position 'square' -->
<!-- BBelements AdServer one2many Pozice: go.cz.bbelements.com AbcLinuxu.cz(14398) / Zbytek webu(2) / square dynamic(14) / square(2)-->
<!-- HowTo: Place this code into the html page there the ad should appear. -->
<div id='bmone2n-14398.2.14.2'>
<noscript><div style='display:inline'><a href='http://go.cz.bbelements.com/please/redirect/14398/2/14/2/'><img src='http://go.cz.bbelements.com/please/showit/14398/2/14/2/?typkodu=img' width='0' height='0' style='border-width:0' alt='' /></a></div></noscript>
</div>
    <div class="s_nadpis"><a href="/nej">Nej blogů na AbcLinuxu</a></div>
    <div class="s_sekce">
            <b>Nejčtenější za poslední měsíc</b>
            <ul>
                    <li><a href="/blog/lINUKS/2014/7/ukrajinska-sbu-ma-na-svych-pc-spatne-nastavenej-cas">Ukrajinská SBU má na svých PC špatně nastavenej čas</a></li>
                    <li><a href="/blog/paulovo_doupe/2014/7/facebook-jako-spolecenska-povinnost">Facebook jako společenská povinnost?</a></li>
                    <li><a href="/blog/Untitled/2014/7/par-triku-pro-shell">Pár triků pro shell</a></li>
            </ul>

            <b>Nejkomentovanější za poslední měsíc</b>
            <ul>
                    <li><a href="/blog/lINUKS/2014/7/ukrajinska-sbu-ma-na-svych-pc-spatne-nastavenej-cas">Ukrajinská SBU má na svých PC špatně nastavenej čas</a></li>
                    <li><a href="/blog/Kelvin_Fitnick/2014/7/donecky-bloody-sunday">Doněcký Bloody Sunday</a></li>
                    <li><a href="/blog/hansovo/2014/7/rms-na-tedx">RMS na TEDx</a></li>
            </ul>
    </div>

<!-- the advertisement position hypertext2dole is not active -->

            </div></div> <!-- ps, s -->
        </div> <!-- obal_ps -->

    <div class="st" id="st">
        <a name="obsah"></a>

<!-- the advertisement position obsah-box-uzky is not active -->
            <div class="pwd-box">
                <div class="do-zalozek">
                        <a href="/auto/blog/pyx.rss"><img src="/images/site2/feed16.png" width="16" height="16" border="0"></a>
                </div>
                <div class="pwd">
                    <a href="/">AbcLinuxu</a>:/
                        <a href="/blog;jsessionid=10c41aylm66sz1slub26ivrblx">Blogy</a>
                         / 
                        <a href="/blog/pyx;jsessionid=10c41aylm66sz1slub26ivrblx">h8blog</a>
                        
                </div>
            </div>





    <div class="cl">
        <h2 class="st_nadpis">
            <a href="/blog/pyx/2011/10/tisickrat-nic-umorilo-osla-ubuntu-11.10">Tisíckrát nic umořilo osla (Ubuntu 11.10)</a>
        </h2>
        <p class="meta-vypis">
            22.10.2011 13:41
                    | <a href="/blog/pyx/tecka" title="Kategorie zápisu">tečka (.)</a>
            
            
            | Přečteno: 3487&times;
            |     <a href="/blog/pyx/2011/10/tisickrat-nic-umorilo-osla-ubuntu-11.10/diskuse">Komentářů:&nbsp;116</a>, poslední&nbsp;26. 10. 2011

    | Hodnocení:&nbsp;67&nbsp;%&nbsp;(6&nbsp;hlasů)
        </p>
                <p>Jak jsem napsal, tak jsem taky udělal. Zkusil jsem používat nové Ubuntu bez velkých úprav. Jeden z těch 'bannerů' při instalaci tvrdí, že Ubuntu může používat každý. S výhradami. Přidávám poznámky ze začátků používání.</p>

                <div class="signature"><a href="/blog/pyx/2011/10/tisickrat-nic-umorilo-osla-ubuntu-11.10">více...</a></div>
    </div>
    <hr>
    <div class="cl">
        <h2 class="st_nadpis">
            <a href="/blog/pyx/2011/10/sedm-let-ubuntu">Sedm let Ubuntu</a>
        </h2>
        <p class="meta-vypis">
            20.10.2011 23:52
                    | <a href="/blog/pyx/vykricnik" title="Kategorie zápisu">vykřičník (!)</a>
            
            
            | Přečteno: 1395&times;
            |     <a href="/blog/pyx/2011/10/sedm-let-ubuntu/diskuse">Komentářů:&nbsp;49</a>, poslední&nbsp;23. 10. 2011

    | Hodnocení:&nbsp;56&nbsp;%&nbsp;(9&nbsp;hlasů)
        </p>
                <p>Podle <a href="http://linux.slashdot.org/story/11/10/20/1320231/ubuntu-turns-7">/.</a> má Ubuntu slavit sedmé narozeniny.</p>

                <div class="signature"><a href="/blog/pyx/2011/10/sedm-let-ubuntu">více...</a></div>
    </div>
    <hr>
    <div class="cl">
        <h2 class="st_nadpis">
            <a href="/blog/pyx/2011/10/anketa-nejlepsi-vylepseni-pc">Anketa: Nejlepší vylepšení PC</a>
        </h2>
        <p class="meta-vypis">
            16.10.2011 20:07
                    | <a href="/blog/pyx/otaznik" title="Kategorie zápisu">otazník (?)</a>
            
            
            | Přečteno: 1446&times;
            |     <a href="/blog/pyx/2011/10/anketa-nejlepsi-vylepseni-pc/diskuse">Komentářů:&nbsp;49</a>, poslední&nbsp;25. 10. 2011

    | Hodnocení:&nbsp;100&nbsp;%&nbsp;(3&nbsp;hlasů)
        </p>
                <p>Jaké vylepšení PC pro vás bylo nejlepší, nejvíce vám usnadnilo používání? Přišlo mi to jako pozoruhodný námět k zamyšlení. (Na /. teď běží <a href="http://linux.slashdot.org/poll/2254/the-best-computer-upgrade-ive-ever-done-was">zajímavé hlasování</a>, tak jsem se jím inspiroval.)</p>

                <div class="signature"><a href="/blog/pyx/2011/10/anketa-nejlepsi-vylepseni-pc">více...</a></div>
    </div>
    <hr>
    <div class="cl">
        <h2 class="st_nadpis">
            <a href="/blog/pyx/2011/10/efektivni-psani-pracovni-report-2">Efektivní psaní (pracovní report 2)</a>
        </h2>
        <p class="meta-vypis">
            7.10.2011 21:46
                    | <a href="/blog/pyx/strednik" title="Kategorie zápisu">středník (;)</a>
            
            
            | Přečteno: 1348&times;
            |     <a href="/blog/pyx/2011/10/efektivni-psani-pracovni-report-2/diskuse">Komentářů:&nbsp;30</a>, poslední&nbsp;9. 10. 2011

    | Hodnocení:&nbsp;80&nbsp;%&nbsp;(5&nbsp;hlasů)
        </p>
                <p>Před dvěma měsíci jsem tu psal o svých <a href="/blog/pyx/2011/5/efektivni-psani-pracovni-report">plánech ohledně psaní na klávesnici</a>. Shrnu své prozatimní zkušenosti s rozvržením klávesnice <a href="http://colemak.com/">Colemak</a>.</p>

                <div class="signature"><a href="/blog/pyx/2011/10/efektivni-psani-pracovni-report-2">více...</a></div>
    </div>
    <hr>
    <div class="cl">
        <h2 class="st_nadpis">
            <a href="/blog/pyx/2011/10/blog-occupy-wall-street">μblog: Occupy Wall Street</a>
        </h2>
        <p class="meta-vypis">
            3.10.2011 22:23
                    | <a href="/blog/pyx/vykricnik" title="Kategorie zápisu">vykřičník (!)</a>
            
            
            | Přečteno: 1042&times;
            |     <a href="/blog/pyx/2011/10/blog-occupy-wall-street/diskuse">Komentářů:&nbsp;45</a>, poslední&nbsp;6. 10. 2011

    | Hodnocení:&nbsp;86&nbsp;%&nbsp;(7&nbsp;hlasů)
        </p>
                <p>Akci <a href="http://occupywallst.org/">Occupy Wall Street</a> jsem zaregistroval v podstatě náhodou.</p>

                <div class="signature"><a href="/blog/pyx/2011/10/blog-occupy-wall-street">více...</a></div>
    </div>
    <hr>
    <div class="cl">
        <h2 class="st_nadpis">
            <a href="/blog/pyx/2011/10/verny-spojenec-a-vzor-demokraticke-spolecnosti">Věrný spojenec a vzor demokratické společnosti</a>
        </h2>
        <p class="meta-vypis">
            2.10.2011 14:51
                    | <a href="/blog/pyx/vykricnik" title="Kategorie zápisu">vykřičník (!)</a>
            
            
            | Přečteno: 1189&times;
            |     <a href="/blog/pyx/2011/10/verny-spojenec-a-vzor-demokraticke-spolecnosti/diskuse">Komentářů:&nbsp;28</a>, poslední&nbsp;4. 10. 2011

    | Hodnocení:&nbsp;100&nbsp;%&nbsp;(5&nbsp;hlasů)
        </p>
                <p>Zase jsem se nasral. <a href="http://online.wsj.com/article/SB10001424052970204138204576602301252340820.html">Bezpilotní bojová mašina pacifikovala teroristu</a> (WSJ)</p>

                <div class="signature"><a href="/blog/pyx/2011/10/verny-spojenec-a-vzor-demokraticke-spolecnosti">více...</a></div>
    </div>
    <hr>

<p>
</p>

	</div> <!-- st -->

    <div class="s_nadpis linkbox_nadpis">Píšeme jinde</div>
    
<div class="linkbox kontejner noext">
    <table border="0">
        <tr>
                <td style="vertical-align:top">
                    <a href="http://www.itbiz.cz/clanky/kauza-opencard-technologicky-pohled?utm_medium=linkbox&utm_campaign=linkbox" title="Kauza Opencard: technologický vs. politický pohled "><img src="http://linkbox.argonit.cz/images/kauza-opencard-technologicky-vs-politicky-pohled.JPG" width="180" height="120" alt="Kauza Opencard: technologický vs. politický pohled "></a>
                    <p class="nazev_clanku"><a href="http://www.itbiz.cz/clanky/kauza-opencard-technologicky-pohled?utm_medium=linkbox&utm_campaign=linkbox">Kauza Opencard: technologický vs. politický pohled </a></p>
                </td>
                <td style="vertical-align:top">
                    <a href="http://hdmag.cz/clanek/hd-zvuk-4-av-receivery?utm_medium=linkbox&utm_campaign=linkbox" title="HD Zvuk #4: AV Receivery"><img src="http://linkbox.argonit.cz/images/hd-zvuk-4-av-receivery.jpg" width="180" height="120" alt="HD Zvuk #4: AV Receivery"></a>
                    <p class="nazev_clanku"><a href="http://hdmag.cz/clanek/hd-zvuk-4-av-receivery?utm_medium=linkbox&utm_campaign=linkbox">HD Zvuk #4: AV Receivery</a></p>
                </td>
                <td style="vertical-align:top">
                    <a href="http://www.abclinuxu.cz/clanky/zpravodaj-o-vine-4.-9.-2013-vykonnostni-vylepseni-direct3d?utm_medium=linkbox&utm_campaign=linkbox" title="Rychlejší Direct3D ve Wine"><img src="http://linkbox.argonit.cz/images/rychlejsi-direct3d-ve-wine.png" width="180" height="120" alt="Rychlejší Direct3D ve Wine"></a>
                    <p class="nazev_clanku"><a href="http://www.abclinuxu.cz/clanky/zpravodaj-o-vine-4.-9.-2013-vykonnostni-vylepseni-direct3d?utm_medium=linkbox&utm_campaign=linkbox">Rychlejší Direct3D ve Wine</a></p>
                </td>
                <td style="vertical-align:top">
                    <a href="http://hdmag.cz/bleskovka/sony-predstavila-novy-3d-projektor?utm_source=itbiz&utm_medium=sidebar?utm_medium=linkbox&utm_campaign=linkbox" title="Sony představila nový 3D projektor"><img src="http://linkbox.argonit.cz/images/sony-predstavila-novy-3d-projektor.jpg" width="180" height="120" alt="Sony představila nový 3D projektor"></a>
                    <p class="nazev_clanku"><a href="http://hdmag.cz/bleskovka/sony-predstavila-novy-3d-projektor?utm_source=itbiz&utm_medium=sidebar?utm_medium=linkbox&utm_campaign=linkbox">Sony představila nový 3D projektor</a></p>
                </td>
                <td style="vertical-align:top">
                    <a href="http://www.itbiz.cz/clanky/bezpecnostni-prehled-ms-emet-lze-obejit?utm_medium=linkbox&utm_campaign=linkbox" title="Bezpečnostní přehled: Ukradené 4 miliardy dolarů a jak lze obejít MS EMET"><img src="http://www.itbiz.cz/images/upload/k/kreditni-karty_s.jpg" width="180" height="120" alt="Bezpečnostní přehled: Ukradené 4 miliardy dolarů a jak lze obejít MS EMET"></a>
                    <p class="nazev_clanku"><a href="http://www.itbiz.cz/clanky/bezpecnostni-prehled-ms-emet-lze-obejit?utm_medium=linkbox&utm_campaign=linkbox">Bezpečnostní přehled: Ukradené 4 miliardy dolarů a jak lze obejít MS EMET</a></p>
                </td>
        </tr>
    </table>
</div>

    <div class="dl noext">
		<div class="dl_vlevo">ISSN 1214-1267 &nbsp; Powered by
			<a href="http://www.hosting90.cz" title="Server hosting, VPS, virtuální servery, webhosting">Hosting 90</a>
			<a href="http://www.hosting90.cz"><img src="/images/clanky/reklama/hosting90.png" alt="Server hosting" style="vertical-align: bottom; padding-left: 1ex"></a>
			
<script src="/data/btc/coin.js"></script>
<script>
CoinWidgetCom.go({
	wallet_address: "1JgBMeghfnr1rnbbCPXbzvUPuw11bYBBEQ"
	, currency: "bitcoin"
	, counter: "hide"
	, alignment: "ac"
	, qrcode: false
	, auto_show: false
	, lbl_button: "Přispějte"
	, lbl_address: "Adresa BitCoin:"
	, lbl_count: "příspěvků"
	, lbl_amount: "BTC"
});
</script>

        </div>
		<div class="dl_vpravo">
            <a href="/redakce">Redakce</a> |
            <a href="/reklama">Inzerce</a> |
            <a href="/doc/podminky-pouziti">Podmínky použití</a> |
            <a href="/doc/osobni-udaje">Osobní údaje</a>
        </div>
		&copy; 1999-2013 <a href="http://www.argonit.cz">Argonit s. r. o.</a> Všechna práva vyhrazena.
	</div>

</div> <!-- obal -->

<!-- ad position 'gg-anal' -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-3151434-1");
pageTracker._initData();
pageTracker._trackPageview();
</script><!-- ad position 'ad-end' -->
<!-- BBelements one2many code -->
<!-- HowTo: All the ad codes must be above this code! -->
<!-- HowTo: It is good idea to place this code just below the last ad code. -->
<!-- https://go.eu.bbelements.com/bb/bb_one2n.js -->
<script type="text/javascript" charset='utf-8' src="https://go.eu.bbelements.com/bb/bb_one2n.js"></script>

<script type='text/javascript'>/* <![CDATA[ */ 
bmone2n.addPosition('14398.1.8.1','');
bmone2n.addPosition('14398.1.4.64','');
bmone2n.addPosition('14398.1.2.64','');
bmone2n.addPosition('14398.1.3.64','');
bmone2n.addPosition('14398.1.5.64','');
bmone2n.addPosition('14398.1.7.64','');
bmone2n.addPosition('14398.1.8.1','');
bmone2n.addPosition('14398.1.1.2','');
bmone2n.addPosition('14398.2.8.1','');
bmone2n.addPosition('14398.2.4.64','');
bmone2n.addPosition('14398.2.2.64','');
bmone2n.addPosition('14398.2.3.64','');
bmone2n.addPosition('14398.2.5.64','');
bmone2n.addPosition('14398.2.7.64','');
bmone2n.addPosition('14398.2.1.2','');
bmone2n.addPosition('14398.2.8.1','');
bmone2n.addPosition('14398.2.14.2','');
bmone2n.addPosition('14398.1.14.2','');
bmone2n.addPosition('14398.1.4.7','');
bmone2n.addPosition('14398.2.4.1','');


bmone2n.getAd('go.eu.bbelements.com','',''+(typeof(bburlparam)=='string'?'&'+bburlparam:''));
/* ]]> */</script>
<div id='bmone2t-14398.1.8.1' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.8.1'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.4.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.4.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.2.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.2.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.3.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.3.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.5.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.5.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.7.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.7.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.1.2' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.1.2'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.8.1' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.8.1'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.4.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.4.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.2.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.2.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.3.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.3.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.5.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.5.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.7.64' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.7.64'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.1.2' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.1.2'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.14.2' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.14.2'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.14.2' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.14.2'); /* ]]> */</script></div>
<div id='bmone2t-14398.1.4.7' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.1.4.7'); /* ]]> */</script></div>
<div id='bmone2t-14398.2.4.1' style='display:none'><script type='text/javascript'>/* <![CDATA[ */ bmone2n.makeAd('14398.2.4.1'); /* ]]> */</script></div>
<script type='text/javascript'>/* <![CDATA[ */ bmone2n.moveAd(); /* ]]> */</script>
</body>
</html>

