http://www.lurkmore.com/wiki/Category:Project_E.N.I.S
HTTP/1.1 200 OK
Date: Wed, 23 Jul 2014 10:00:19 GMT
Server: Apache
X-Powered-By: PHP/5.4.4-14+deb7u12
X-Content-Type-Options: nosniff
Content-language: en
Vary: Accept-Encoding,Cookie
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: private, must-revalidate, max-age=0
Last-Modified: Fri, 20 Dec 2013 18:12:03 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: sameorigin
Content-Encoding: gzip
Content-Length: 9218
Connection: close
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html lang="en" dir="ltr" class="client-nojs">
<head>
<meta charset="UTF-8" />
<title>Category:Project E.N.I.S. - The LURKMORE Wiki</title>
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
<meta name="generator" content="MediaWiki 1.23.0" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="search" type="application/opensearchdescription+xml" href="/w/opensearch_desc.php" title="LURKMORE wiki (en)" />
<link rel="copyright" href="/wiki/MediaWiki:Copyright" />
<link rel="alternate" type="application/atom+xml" title="LURKMORE wiki Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" />
<link rel="canonical" href="/wiki/Category:Project_E.N.I.S." />
<link rel="stylesheet" href="http://www.lurkmore.com/w/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.ui.button%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook&amp;*" />
<!--[if IE 6]><link rel="stylesheet" href="/w/skins/monobook/IE60Fixes.css?303" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="/w/skins/monobook/IE70Fixes.css?303" media="screen" /><![endif]--><meta name="ResourceLoaderDynamicStyles" content="" />
<link rel="stylesheet" href="http://www.lurkmore.com/w/load.php?debug=false&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=monobook&amp;*" />
<style>a:lang(ar),a:lang(kk-arab),a:lang(mzn),a:lang(ps),a:lang(ur){text-decoration:none}
/* cache key: wiki_lurkmore-wiki_:resourceloader:filter:minify-css:7:4dcaf233d37345bc2198604dcffa1fb4 */</style>
<script src="http://www.lurkmore.com/w/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgCanonicalNamespace":"Category","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":14,"wgPageName":"Category:Project_E.N.I.S.","wgTitle":"Project E.N.I.S.","wgCurRevisionId":22522,"wgRevisionId":22522,"wgArticleId":3791,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["4chan","Memes and terms"],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Category:Project_E.N.I.S.","wgIsProbablyEditable":false,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgRedirectedFrom":"Category:Project_E.N.I.S"});
}</script><script>if(window.mw){
mw.loader.implement("user.options",function($,jQuery){mw.user.options.set({"ccmeonemails":0,"cols":80,"date":"default","diffonly":0,"disablemail":0,"editfont":"default","editondblclick":0,"editsectiononrightclick":0,"enotifminoredits":0,"enotifrevealaddr":0,"enotifusertalkpages":1,"enotifwatchlistpages":1,"extendwatchlist":0,"fancysig":0,"forceeditsummary":0,"gender":"unknown","hideminor":0,"hidepatrolled":0,"imagesize":2,"math":1,"minordefault":0,"newpageshidepatrolled":0,"nickname":"","norollbackdiff":0,"numberheadings":0,"previewonfirst":0,"previewontop":1,"rcdays":7,"rclimit":50,"rows":25,"showhiddencats":0,"shownumberswatching":1,"showtoolbar":1,"skin":"monobook","stubthreshold":0,"thumbsize":2,"underline":2,"uselivepreview":0,"usenewrc":0,"watchcreations":1,"watchdefault":1,"watchdeletion":0,"watchlistdays":3,"watchlisthideanons":0,"watchlisthidebots":0,"watchlisthideliu":0,"watchlisthideminor":0,"watchlisthideown":0,"watchlisthidepatrolled":0,"watchmoves":0,"wllimit":250,
"useeditwarning":1,"prefershttps":1,"language":"en","variant-gan":"gan","variant-iu":"iu","variant-kk":"kk","variant-ku":"ku","variant-shi":"shi","variant-sr":"sr","variant-tg":"tg","variant-uz":"uz","variant-zh":"zh","searchNs0":true,"searchNs1":false,"searchNs2":false,"searchNs3":false,"searchNs4":false,"searchNs5":false,"searchNs6":false,"searchNs7":false,"searchNs8":false,"searchNs9":false,"searchNs10":false,"searchNs11":false,"searchNs12":false,"searchNs13":false,"searchNs14":false,"searchNs15":false,"searchNs274":false,"searchNs275":false,"variant":"en"});},{},{});mw.loader.implement("user.tokens",function($,jQuery){mw.user.tokens.set({"editToken":"+\\","patrolToken":false,"watchToken":false});},{},{});
/* cache key: wiki_lurkmore-wiki_:resourceloader:filter:minify-js:7:faaedd390b818cfe87877143e1615d5a */
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
</head>
<body class="mediawiki ltr sitedir-ltr ns-14 ns-subject page-Category_Project_E_N_I_S skin-monobook action-view">
<div id="globalWrapper">
<div id="column-content"><div id="content" class="mw-body-primary" role="main">
	<a id="top"></a>
<!-- include bitcoin -->
<div style="background:#cef2e0;border:1px solid #aaa;border-radius:0.5em;font-size:12px;margin:4px 0px 0px 0px;padding:0px 6px;max-width:710px;min-width:710px;text-align:center;">
 &hearts; <strong><a href="/wiki/Bitcoin" style="background:none;" title="Learn about Bitcoins">donate bitcoins</a></strong>: <a href="bitcoin:1JsbEn3pVJcWKGE24hiV5eJSGSTzNT2rTw" style="background:none;" title="Donate Bitcoins to the LURKMORE Wiki.">1JsbEn3pVJcWKGE24hiV5eJSGSTzNT2rTw</a> &hearts; <strong><a href="/wiki/Litecoin" style="background:none;" title="Learn about Litecoins">donate litecoins</a></strong>: <a href="litecoin:LTfZmMMiNDVx4uWgntmBYubYHjoVqvxsYZ" style="background:none;" title="Donate Litecoins to the LURKMORE Wiki.">LTfZmMMiNDVx4uWgntmBYubYHjoVqvxsYZ</a> &hearts;
</div><!-- end -->
	
	<h1 id="firstHeading" class="firstHeading" lang="en"><span dir="auto">Category:Project E.N.I.S.</span></h1>
	<div id="bodyContent" class="mw-body">
		<div id="siteSub">From LURKMORE wiki</div>
		<div id="contentSub">(Redirected from <a href="/w/index.php?title=Category:Project_E.N.I.S&amp;redirect=no" title="Category:Project E.N.I.S">Category:Project E.N.I.S</a>)</div>
		<div id="jump-to-nav" class="mw-jump">Jump to: <a href="#column-one">navigation</a>, <a href="#searchInput">search</a></div>

		<!-- start content -->
<div id="mw-content-text" lang="en" dir="ltr" class="mw-content-ltr"><div class="center"><div class="floatnone"><a href="/wiki/File:Project_ENIS_Title.png" class="image"><img alt="Project ENIS Title.png" src="/w/images/c/c5/Project_ENIS_Title.png" width="392" height="479" /></a></div></div>
<p><i>Welcome to <b>Project E.N.I.S.</b>, a <a href="/wiki//m/" title="/m/">/m/-original mecha</a>.</i>
</p><p>Project E.N.I.S originated in the /m/echa section of <a href="/wiki/4chan" title="4chan" class="mw-redirect">4chan</a>. It all began as a project to create a new mecha by adding shapes &amp; components to a single triangle. After only a few parts were added, some <a href="/wiki/Anonymous" title="Anonymous">Anonymous</a> wrote the word "PENIS" on its chest.  But, instead of removing it, the /m/echanoids went along with it and worked the "P" into the design. This left the word "ENIS" on the left part of its chest, thus giving the unit its unique name. 
</p><p>This single thread sparked a wildfire of artistic and literary creations on /m/, with all kinds of /m/-original mecha being created and fleshed out to the great delight of our /m/etalheads.
</p>
<div id="toc" class="toc"><div id="toctitle"><h2>Contents</h2></div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#Select_item"><span class="tocnumber">1</span> <span class="toctext">Select item</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Factions"><span class="tocnumber">2</span> <span class="toctext">Factions</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Units"><span class="tocnumber">3</span> <span class="toctext">Units</span></a>
<ul>
<li class="toclevel-2 tocsection-4"><a href="#Misc_Mecha"><span class="tocnumber">3.1</span> <span class="toctext">Misc Mecha</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-5"><a href="#Characters"><span class="tocnumber">4</span> <span class="toctext">Characters</span></a></li>
<li class="toclevel-1 tocsection-6"><a href="#Episode_Outlines"><span class="tocnumber">5</span> <span class="toctext">Episode Outlines</span></a>
<ul>
<li class="toclevel-2 tocsection-7"><a href="#Episode_One"><span class="tocnumber">5.1</span> <span class="toctext">Episode One</span></a></li>
<li class="toclevel-2 tocsection-8"><a href="#Episode_Two"><span class="tocnumber">5.2</span> <span class="toctext">Episode Two</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-9"><a href="#Story_Chapters.2FEpisodes"><span class="tocnumber">6</span> <span class="toctext">Story Chapters/Episodes</span></a>
<ul>
<li class="toclevel-2 tocsection-10"><a href="#Episode_1:_The_End_of_the_Beginning"><span class="tocnumber">6.1</span> <span class="toctext">Episode 1: The End of the Beginning</span></a></li>
<li class="toclevel-2 tocsection-11"><a href="#Episode_2:_Blaze_in_the_Night"><span class="tocnumber">6.2</span> <span class="toctext">Episode 2: Blaze in the Night</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-12"><a href="#Miscellaneous"><span class="tocnumber">7</span> <span class="toctext">Miscellaneous</span></a></li>
<li class="toclevel-1 tocsection-13"><a href="#Wiki_note"><span class="tocnumber">8</span> <span class="toctext">Wiki note</span></a></li>
<li class="toclevel-1 tocsection-14"><a href="#Related_articles"><span class="tocnumber">9</span> <span class="toctext">Related articles</span></a></li>
</ul>
</div>

<h2><span class="mw-headline" id="Select_item">Select item</span></h2>
<ul>
<li> <a href="/wiki/Project_E.N.I.S._F.A.Q" title="Project E.N.I.S. F.A.Q">Project E.N.I.S. F.A.Q</a>
</li>
</ul>
<h2><span class="mw-headline" id="Factions">Factions</span></h2>
<ul>
<li> <a href="/wiki/Lion_Empire" title="Lion Empire">Lion Empire</a>
</li>
<li> <a href="/wiki/Federation_of_Allied_Planets" title="Federation of Allied Planets">Federation of Allied Planets</a>
</li>
<li> <a href="/wiki/Project_ENIS" title="Project ENIS">Project ENIS</a>
</li>
</ul>
<h2><span class="mw-headline" id="Units">Units</span></h2>
<ul>
<li> <a href="/wiki/Project_ENIS#Units" title="Project ENIS">Project ENIS Mecha</a>
</li>
<li> <a href="/wiki/Federation_of_Allied_Planets#Units" title="Federation of Allied Planets">FAP Mecha</a>
</li>
<li> <a href="/wiki/Lion_Empire#Units" title="Lion Empire">Lion Empire Mecha</a>
</li>
</ul>
<h4><span class="mw-headline" id="Misc_Mecha">Misc Mecha</span></h4>
<ul>
<li> <a href="/wiki/Rust_Busters" title="Rust Busters" class="mw-redirect">Rust Busters</a>
</li>
<li> <a href="/wiki/RyuKaiGan" title="RyuKaiGan">RyuKaiGan</a>
</li>
<li> <a href="/wiki/RM-02" title="RM-02">RM-02</a>
</li>
</ul>
<h2><span class="mw-headline" id="Characters">Characters</span></h2>
<table>
<tr>
<td style="width:150px;">
<ul>
<li> <a href="/wiki/Ada_Zul/Zuru" title="Ada Zul/Zuru">Ada Zul/Zuru</a>
</li>
<li> <a href="/wiki/D" title="D">D</a>
</li>
<li> <a href="/wiki/Dr._Dame_Olga" title="Dr. Dame Olga">Dr. Dame Olga</a>
</li>
</ul>
</td>
<td style="width:150px;">
<ul>
<li> <a href="/wiki/Daisuke_Ryokija" title="Daisuke Ryokija">Daisuke Ryokija</a>
</li>
<li> <a href="/wiki/Kijani" title="Kijani">Kijani</a>
</li>
<li> <a href="/wiki/Kobayashi_Ohta" title="Kobayashi Ohta">Kobayashi Ohta</a>
</li>
</ul>
</td>
<td style="width:150px;">
<ul>
<li> <a href="/wiki/Noland_Abrams" title="Noland Abrams">Noland Abrams</a>
</li>
<li> <a href="/wiki/Norma" title="Norma">Norma</a>
</li>
<li> <a href="/wiki/Professor_M" title="Professor M">Professor M</a>
</li>
</ul>
</td>
<td style="width:175px;">
<ul>
<li> <a href="/wiki/Sven_Vladi" title="Sven Vladi">Sven Vladi</a>
</li>
<li> <a href="/wiki/Thanatos_Zmake_Ronero" title="Thanatos Zmake Ronero">Thanatos Zmake Ronero</a>
</li>
<li> <a href="/wiki/Yuan_Nomos" title="Yuan Nomos">Yuan Nomos</a>
</li>
</ul>
</td></tr></table>
<h2><span class="mw-headline" id="Episode_Outlines">Episode Outlines</span></h2>
<h3><span class="mw-headline" id="Episode_One">Episode One</span></h3>
<p>Professor is in ENIS and fighting Noland in a modified grunt mech. The two are pretty evenly matched, until the Professor uses ENIS' special move, but Noland gets the upper hand and sends him plummeting to the ground below. As he falls, the professor shouts some bad-ass line about how 'He'll finish off the Lions, even after he has died.' 
</p><p>Ohta is mining. Suddenly, a huge quake hits that causes a cave-in. He finds himself trapped by the cave-in and heads through the mines and finds that the quake was caused by the crash-landed ENIS. The professor, who thought he was going to die alone, begins laughing even as he bleeds, because here's someone who he can make into a pilot. He shoves Ohta into the machine and forces the piloting control into his hand, his final act and a way of saying "FUCK YOU" to the Lions in passing. The Professor tells Ohta there's going to be a Lion Empire invasion, and sees him off before passing away.
</p><p>As Ohta and ENIS head for their home city, and find it under attack by one of the Lion Empire's racial fleets. He fights them off in the city for a bit before almost losing to the Super leading the invasion, but manages to escape. He picks up a garbled message from the Evaikari government, and decides to escort evacuating ships. Thus Ohta leaves the planet, while a massive Lion Empire fleet orbits and Noland realizes that ENIS survived and thinks the Professor survived too.
</p>
<h3><span class="mw-headline" id="Episode_Two">Episode Two</span></h3>
<p>Ohta fights off an enemy attack on the evacuating fleet as it rushes towards the edge of the system and the hyperspace routes towards FAP. The Super from the first episode returns and Ohta, still not familiar with ENIS, is almost killed, but is saved by Daisuke Ryokija in Wingschneider. White Knight picks up Ohta and he meets the scientist crew, who will eventually become Project Enis. They decide to help him escort the civilians to safety. Some discussion with the scientists reveals some of ENIS' potential to Ohta, but before he can learn more they reach the edge of the system and fight off an attack by the Grays. Ohta manages to finally get the upper hand on Im.C.M.L and defeats it, but just as White Knight is preparing to jump into hyperspace, it is knocked off its launch trajectory and sent rocketing off into Lion Empire territory.
</p>
<h2><span class="mw-headline" id="Story_Chapters.2FEpisodes">Story Chapters/Episodes</span></h2>
<h3><span class="mw-headline" id="Episode_1:_The_End_of_the_Beginning">Episode 1: The End of the Beginning</span></h3>
<ul>
<li> <a href="/wiki/Project_E.N.I.S._Chapters#Prologue:_The_End_of_the_Beginning" title="Project E.N.I.S. Chapters">Prologue: The End of the Beginning</a>
</li>
<li> <a href="/wiki/Project_E.N.I.S._Chapters#Chapter_1:_CroSSiNG_THE_LiNE" title="Project E.N.I.S. Chapters">Chapter 1: CroSSiNG THE LiNE</a>
</li>
<li> <a href="/wiki/Project_E.N.I.S._Chapters#Chapter_2:_StORm_of_THuNDeR" title="Project E.N.I.S. Chapters">Chapter 2: StORm of THuNDeR</a>
</li>
<li> <a href="/wiki/Project_E.N.I.S._Chapters#Chapter_3:_Winging_to_the_Night" title="Project E.N.I.S. Chapters">Chapter 3: Winging to the Night</a>
</li>
</ul>
<h3><span class="mw-headline" id="Episode_2:_Blaze_in_the_Night">Episode 2: Blaze in the Night</span></h3>
<h2><span class="mw-headline" id="Miscellaneous">Miscellaneous</span></h2>
<ul>
<li> <a href="/wiki/Project_E.N.I.S._Audio_Dump" title="Project E.N.I.S. Audio Dump">Project E.N.I.S. Audio Dump</a>
</li>
<li> <a href="/wiki/Project_E.N.I.S._Concept_Work" title="Project E.N.I.S. Concept Work">Project E.N.I.S. Concept Work</a>
</li>
<li> <a href="/wiki/Project_E.N.I.S._Image_Dump" title="Project E.N.I.S. Image Dump">Project E.N.I.S. Image Dump</a>
</li>
<li> <a href="/wiki/Project_E.N.I.S._Suggestions" title="Project E.N.I.S. Suggestions">Project E.N.I.S. Suggestions</a>
</li>
<li> <a href="/wiki/Project_E.N.I.S._Text_Dump" title="Project E.N.I.S. Text Dump">Project E.N.I.S. Text Dump</a>
</li>
</ul>
<h2><span class="mw-headline" id="Wiki_note">Wiki note</span></h2>
<p>Add [[Category:Project E.N.I.S.]] to any page to add it to the Project E.N.I.S. category.
</p>
<h2><span class="mw-headline" id="Related_articles">Related articles</span></h2>
<ul>
<li> <a href="/wiki//m/" title="/m/">/m/</a>
</li>
<li> <a href="/wiki/Project_SRW/m/" title="Project SRW/m/" class="mw-redirect">Project SRW/m/</a>
</li>
</ul>

<!-- 
NewPP limit report
CPU time usage: 0.092 seconds
Real time usage: 0.161 seconds
Preprocessor visited node count: 64/1000000
Preprocessor generated node count: 80/1000000
Post‐expand include size: 0/2097152 bytes
Template argument size: 0/2097152 bytes
Highest expansion depth: 2/40
Expensive parser function count: 0/100
-->

<!-- Saved in parser cache with key wiki_lurkmore-wiki_:pcache:idhash:3791-0!*!0!!en!2!* and timestamp 20140723040521 and revision id 22522
 -->
<div lang="en" dir="ltr"><div id="mw-pages">
<h2>Pages in category "Project E.N.I.S."</h2>
<p>The following 60 pages are in this category, out of 60 total.
</p><div lang="en" dir="ltr" class="mw-content-ltr"><table style="width: 100%;"><tr style="vertical-align: top;"><td style="width: 33.3%;"><h3>A</h3>
<ul><li><a href="/wiki/A-NL" title="A-NL">A-NL</a></li>
<li><a href="/wiki/Ada_Zul/Zuru" title="Ada Zul/Zuru">Ada Zul/Zuru</a></li>
<li><a href="/wiki/Attack_Craft" title="Attack Craft">Attack Craft</a></li></ul><h3>B</h3>
<ul><li><a href="/wiki/Battleships" title="Battleships">Battleships</a></li>
<li><a href="/wiki/Behemoth" title="Behemoth">Behemoth</a></li>
<li><a href="/wiki/BXR-7mk2_%27Godhand%27" title="BXR-7mk2 'Godhand'">BXR-7mk2 'Godhand'</a></li></ul><h3>C</h3>
<ul><li><a href="/wiki/Calypso" title="Calypso">Calypso</a></li>
<li><a href="/wiki/CF-06" title="CF-06">CF-06</a></li>
<li><a href="/wiki/Code_Blue" title="Code Blue">Code Blue</a></li>
<li><a href="/wiki/Cruisers" title="Cruisers">Cruisers</a></li></ul><h3>D</h3>
<ul><li><a href="/wiki/D" title="D">D</a></li>
<li><a href="/wiki/Daisuke_Ryokija" title="Daisuke Ryokija">Daisuke Ryokija</a></li>
<li><a href="/wiki/Dr._Dame_Olga" title="Dr. Dame Olga">Dr. Dame Olga</a></li></ul><h3>E</h3>
<ul><li><a href="/wiki/ENIS" title="ENIS">ENIS</a></li></ul><h3>F</h3>
<ul><li><a href="/wiki/Fackel" title="Fackel">Fackel</a></li>
<li><a href="/wiki/Federation_of_Allied_Planets" title="Federation of Allied Planets">Federation of Allied Planets</a></li>
<li><a href="/wiki/Frigates" title="Frigates">Frigates</a></li></ul><h3>G</h3>
<ul><li><a href="/wiki/GR3-Y_Fox" title="GR3-Y Fox">GR3-Y Fox</a></li>
<li><a href="/wiki/Grays" title="Grays">Grays</a></li></ul><h3>H</h3>
<ul><li><a href="/wiki/Honneamise" title="Honneamise">Honneamise</a></li></ul></td>
<td style="width: 33.3%;"><h3>I</h3>
<ul><li><a href="/wiki/Im.C.M.L" title="Im.C.M.L">Im.C.M.L</a></li></ul><h3>K</h3>
<ul><li><a href="/wiki/Kaminari" title="Kaminari">Kaminari</a></li>
<li><a href="/wiki/Kijani" title="Kijani">Kijani</a></li>
<li><a href="/wiki/Kobayashi_Ohta" title="Kobayashi Ohta">Kobayashi Ohta</a></li></ul><h3>L</h3>
<ul><li><a href="/wiki/Lion_Empire" title="Lion Empire">Lion Empire</a></li>
<li><a href="/wiki/Lion_Empire_Fusion_type_monsters" title="Lion Empire Fusion type monsters">Lion Empire Fusion type monsters</a></li>
<li><a href="/wiki/Lions" title="Lions">Lions</a></li></ul><h3>M</h3>
<ul><li><a href="/wiki/Mass-Produced_ENIS" title="Mass-Produced ENIS">Mass-Produced ENIS</a></li>
<li><a href="/wiki/MB-02" title="MB-02">MB-02</a></li></ul><h3>N</h3>
<ul><li><a href="/wiki/Noland_Abrams" title="Noland Abrams">Noland Abrams</a></li>
<li><a href="/wiki/Norma" title="Norma">Norma</a></li></ul><h3>P</h3>
<ul><li><a href="/wiki/Template:PENISMecha" title="Template:PENISMecha">Template:PENISMecha</a></li>
<li><a href="/wiki/Predamax" title="Predamax">Predamax</a></li>
<li><a href="/wiki/Professor_M" title="Professor M">Professor M</a></li>
<li><a href="/wiki/Project_E.N.I.S._Audio_Dump" title="Project E.N.I.S. Audio Dump">Project E.N.I.S. Audio Dump</a></li>
<li><a href="/wiki/Project_E.N.I.S._Chapters" title="Project E.N.I.S. Chapters">Project E.N.I.S. Chapters</a></li>
<li><a href="/wiki/Project_E.N.I.S._Concept_Work" title="Project E.N.I.S. Concept Work">Project E.N.I.S. Concept Work</a></li>
<li><a href="/wiki/Project_E.N.I.S._F.A.Q" title="Project E.N.I.S. F.A.Q">Project E.N.I.S. F.A.Q</a></li>
<li><a href="/wiki/Project_E.N.I.S._Image_Dump" title="Project E.N.I.S. Image Dump">Project E.N.I.S. Image Dump</a></li>
<li><a href="/wiki/Project_E.N.I.S._Suggestions" title="Project E.N.I.S. Suggestions">Project E.N.I.S. Suggestions</a></li></ul></td>
<td style="width: 33.3%;"><h3>P cont.</h3>
<ul><li><a href="/wiki/Project_E.N.I.S._Text_Dump" title="Project E.N.I.S. Text Dump">Project E.N.I.S. Text Dump</a></li>
<li><a href="/wiki/Project_ENIS" title="Project ENIS">Project ENIS</a></li></ul><h3>R</h3>
<ul><li><a href="/wiki/RAEP" title="RAEP">RAEP</a></li>
<li><a href="/wiki/RaePOST" title="RaePOST">RaePOST</a></li>
<li><a href="/wiki/RM-02" title="RM-02">RM-02</a></li>
<li><a href="/wiki/Rust_Brusters" title="Rust Brusters">Rust Brusters</a></li>
<li><a href="/wiki/RyuKaiGan" title="RyuKaiGan">RyuKaiGan</a></li></ul><h3>S</h3>
<ul><li><a href="/wiki/Surion" title="Surion">Surion</a></li>
<li><a href="/wiki/Sven_Vladi" title="Sven Vladi">Sven Vladi</a></li></ul><h3>T</h3>
<ul><li><a href="/wiki/Thanatos_Zmake_Ronero" title="Thanatos Zmake Ronero">Thanatos Zmake Ronero</a></li>
<li><a href="/wiki/Torirobiter" title="Torirobiter">Torirobiter</a></li>
<li><a href="/wiki/TR4N-Vestite" title="TR4N-Vestite">TR4N-Vestite</a></li>
<li><a href="/wiki/TUL-BAWCS" title="TUL-BAWCS">TUL-BAWCS</a></li></ul><h3>V</h3>
<ul><li><a href="/wiki/VA-INA" title="VA-INA">VA-INA</a></li>
<li><a href="/wiki/Voltage" title="Voltage">Voltage</a></li></ul><h3>W</h3>
<ul><li><a href="/wiki/White_Knight_(Project_ENIS)" title="White Knight (Project ENIS)">White Knight (Project ENIS)</a></li>
<li><a href="/wiki/Wingschneider" title="Wingschneider">Wingschneider</a></li></ul><h3>Y</h3>
<ul><li><a href="/wiki/Yuan_Nomos" title="Yuan Nomos">Yuan Nomos</a></li>
<li><a href="/wiki/Yuki_Unit" title="Yuki Unit">Yuki Unit</a></li></ul><h3>Z</h3>
<ul><li><a href="/wiki/Zalish" title="Zalish">Zalish</a></li></ul></td>
</tr></table></div>
</div></div></div><div class="printfooter">
Retrieved from "<a href="http://www.lurkmore.com/w/index.php?title=Category:Project_E.N.I.S.&amp;oldid=22522">http://www.lurkmore.com/w/index.php?title=Category:Project_E.N.I.S.&amp;oldid=22522</a>"</div>
		<div id='catlinks' class='catlinks'><div id="mw-normal-catlinks" class="mw-normal-catlinks"><a href="/wiki/Special:Categories" title="Special:Categories">Categories</a>: <ul><li><a href="/wiki/Category:4chan" title="Category:4chan">4chan</a></li><li><a href="/wiki/Category:Memes_and_terms" title="Category:Memes and terms">Memes and terms</a></li></ul></div></div>		<!-- end content -->
				<div class="visualClear"></div>
	</div>
</div></div>
<div id="column-one">
	<h2>Navigation menu</h2>
	<div id="p-cactions" class="portlet" role="navigation">
		<h3>Views</h3>
		<div class="pBody">
			<ul>
				<li id="ca-nstab-category" class="selected"><a href="/wiki/Category:Project_E.N.I.S." title="View the category page [c]" accesskey="c">Category</a></li>
				<li id="ca-talk" class="new"><a href="/edit/Category_talk:Project_E.N.I.S.?redlink=1" title="Discussion about the content page [t]" accesskey="t">Discussion</a></li>
				<li id="ca-viewsource"><a href="/edit/Category:Project_E.N.I.S." title="This page is protected.&#10;You can view its source [e]" accesskey="e">View source</a></li>
				<li id="ca-history"><a href="/history/Category:Project_E.N.I.S." rel="archives" title="Past revisions of this page [h]" accesskey="h">History</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-personal" role="navigation">
		<h3>Personal tools</h3>
		<div class="pBody">
			<ul>
				<li id="pt-login"><a href="/w/index.php?title=Special:UserLogin&amp;returnto=Category%3AProject+E.N.I.S." title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in / create account</a></li>
			</ul>
		</div>
	</div>
	<div class="portlet" id="p-logo" role="banner">
<a href="/wiki/Main_page" style="background-image: url(/logo.png);" title="Visit the main page"></a>
	</div>
<!-- GreedBox-->
<div class="pBody" style="height:35px;margin:4px 0px;padding:4px;text-align:center;width:137px;">
 <a href="http://greedbox.com/"><img src="http://greedbox.com/button.php?u=lurkmore" alt="GreedBox Anonymous Imageboard Toplist" style="border:1px solid #00f;height:31px;width:88px;" /></a>
</div>
<!-- end -->
	<div class="generated-sidebar portlet" id="p-navigation" role="navigation">
		<h3>Navigation</h3>
		<div class='pBody'>
			<ul>
				<li id="n-mainpage"><a href="/wiki/Main_page" title="Visit the main page [z]" accesskey="z">Main page</a></li>
				<li id="n-recentchanges"><a href="/wiki/Special:RecentChanges" title="A list of recent changes in the wiki [r]" accesskey="r">Recent changes</a></li>
				<li id="n-randompage"><a href="/wiki/Special:Random" title="Load a random page [x]" accesskey="x">Random page</a></li>
			</ul>
		</div>
	</div>
	<div class="generated-sidebar portlet" id="p-quick_links" role="navigation">
		<h3>quick links</h3>
		<div class='pBody'>
			<ul>
				<li id="n-Memes"><a href="/wiki/Memes">Memes</a></li>
				<li id="n-Memes-and-terms"><a href="/wiki/Category:Memes_and_terms">Memes and terms</a></li>
				<li id="n-4chan"><a href="/wiki/Category:4chan">4chan</a></li>
				<li id="n-Camboys"><a href="/wiki/Category:Camboys">Camboys</a></li>
				<li id="n-Camgirls"><a href="/wiki/Category:Camgirls">Camgirls</a></li>
				<li id="n-Cross-dressers"><a href="/wiki/Category:Cross-dressers">Cross-dressers</a></li>
				<li id="n-Traps"><a href="/wiki/Category:Traps">Traps</a></li>
				<li id="n-IRC"><a href="/wiki/IRC">IRC</a></li>
			</ul>
		</div>
	</div>
	<div class="generated-sidebar portlet" id="p-the_lurkmore_group" role="navigation">
		<h3>the lurkmore group</h3>
		<div class='pBody'>
			<ul>
				<li id="n-The-Overchan-v3"><a href="http://1ch.us">The Overchan v3</a></li>
				<li id="n-irc.lurkmore.com-.23chanchan"><a href="irc://irc.lurkmore.com/chanchan" rel="nofollow">irc.lurkmore.com #chanchan</a></li>
				<li id="n-intern3ts"><a href="http://www.intern3ts.com">intern3ts</a></li>
				<li id="n-chansluts"><a href="http://www.chansluts.com">chansluts</a></li>
				<li id="n-Male-General"><a href="http://www.malegeneral.com">Male General</a></li>
				<li id="n-TranCHAN"><a href="http://www.tranchan.net">TranCHAN</a></li>
				<li id="n-TEXTCHAN"><a href="http://www.textchan.com">TEXTCHAN</a></li>
				<li id="n-GreedBox"><a href="http://www.greedbox.com">GreedBox</a></li>
				<li id="n-penetrate-you"><a href="http://www.penetrat.eu">penetrate you</a></li>
				<li id="n-BabyTurtlesAreCool"><a href="http://www.babyturtlesarecool.com">BabyTurtlesAreCool</a></li>
			</ul>
		</div>
	</div>
	<div id="p-search" class="portlet" role="search">
		<h3><label for="searchInput">Search</label></h3>
		<div id="searchBody" class="pBody">
			<form action="/w/index.php" id="searchform">
				<input type='hidden' name="title" value="Special:Search"/>
				<input type="search" name="search" placeholder="Search" title="Search LURKMORE wiki [f]" accesskey="f" id="searchInput" />
				<input type="submit" name="go" value="Go" title="Go to a page with this exact name if exists" id="searchGoButton" class="searchButton" />&#160;
				<input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton" />
			</form>

					</div>
	</div>
	<div class="portlet" id="p-tb" role="navigation">
		<h3>Tools</h3>
		<div class="pBody">
			<ul>
				<li id="t-whatlinkshere"><a href="/wiki/Special:WhatLinksHere/Category:Project_E.N.I.S." title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li>
				<li id="t-recentchangeslinked"><a href="/wiki/Special:RecentChangesLinked/Category:Project_E.N.I.S." title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li>
				<li id="t-specialpages"><a href="/wiki/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li>
				<li id="t-print"><a href="/w/index.php?title=Category:Project_E.N.I.S.&amp;printable=yes" rel="alternate" title="Printable version of this page [p]" accesskey="p">Printable version</a></li>
				<li id="t-permalink"><a href="/w/index.php?title=Category:Project_E.N.I.S.&amp;oldid=22522" title="Permanent link to this revision of the page">Permanent link</a></li>
				<li id="t-info"><a href="/info/Category:Project_E.N.I.S.">Page information</a></li>
			</ul>
		</div>
	</div>
</div><!-- end of the left (by default at least) column -->
<div class="visualClear"></div>
<div id="footer" role="contentinfo">
	<div id="f-copyrightico">
		<a href="http://creativecommons.org/licenses/by-nc/3.0/"><img src="http://i.creativecommons.org/l/by-nc/3.0/88x31.png" alt="CC BY-NC" width="88" height="31" /></a>
	</div>
	<div id="f-poweredbyico">
		<a href="//www.mediawiki.org/"><img src="/w/skins/common/images/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31" /></a>
	</div>
	<ul id="f-list">
		<li id="lastmod"> Page last modified 23:19, 27 September 2013.</li>
		<li id="viewcount">Page accessed 12,999 times.</li>
		<li id="copyright">Content is available under the CC BY-NC license. Direct links back to the article must be included.</li>
		<li id="about"><a href="/wiki/LURKMORE_wiki:About" title="LURKMORE wiki:About">About the LURKMORE wiki</a></li>
	</ul>
</div>
</div>
<!-- include ads -->
<div style="background:#ffe;border:1px solid #aaa;padding:6px;position:absolute;top:20px;right:2px;text-align:center;width:160px;z-index:-1;">
 <h3 style="border-bottom:1px solid red;margin-bottom:8px;">Some banner ads</h3>
 <iframe id="tehads1" data-aa="1204" src="//ad.a-ads.com/1204" scrolling="no" style="border:0px;height:600px;overflow:hidden;padding:0;width:160px;"></iframe>
 <br />
 <a href='http://a-ads.com?partner=1204'>Advertise with Anonymous Ads</a>
</div>
<div style="background:#ffe;border:1px solid #aaa;margin:8px;padding:4px;text-align:center;min-width:800px;">
 <iframe id="tehads2" src="http://ads.adonion.com/frameAd.php?user=21401&amp;site=19112&amp;zone=50423" scrolling="no" style="border:0px;height:90px;overflow:hidden;padding:0px;width:728px;"></iframe>
</div>
<script type="text/javascript">
 function refreshad() {
  "use strict";
  $('#tehads0').attr('src', function( i, val ) {return val;});
  $('#tehads1').attr('src', function( i, val ) {return val;});
  $('#tehads2').attr('src', function( i, val ) {return val;});
  setTimeout(function(){refreshad();}, 40000);
 }
 refreshad();
</script><!-- end ads -->
<script>/*<![CDATA[*/window.jQuery && jQuery.ready();/*]]>*/</script><script>if(window.mw){
mw.loader.state({"site":"loading","user":"ready","user.groups":"ready"});
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.action.view.postEdit","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready"],null,true);
}</script>
<script src="http://www.lurkmore.com/w/load.php?debug=false&amp;lang=en&amp;modules=site&amp;only=scripts&amp;skin=monobook&amp;*"></script>
<script>if(window.mw){
mw.config.set({"wgBackendResponseTime":133});
}</script></body></html>
